services:

  # NGINX API Gateway
  nginx:
    image: nginx:alpine-slim
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - mssql
  
  # SQL Server Express
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-express
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
    driver: local